version: '3'

services:

  srv:
    image: bfellows37/pasteapi:latest
    env_file:
      - srv.env
    links:
      - mongo

  app:
    image: bfellows37/paste:latest
    ports:
      - 80:4200
    env_file:
      - app.env
    links:
      - srv

  mongo:
    image: mongo:latest
    volumes:
      - dbdata:/data/db
      - dbconfig:/data/configdb

volumes:
  dbdata:
  dbconfig:
